// <auto-generated />
using System;
using ExchangeApp.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExchangeApp.DAL.Migrations
{
    [DbContext(typeof(ExchangeAppDbContext))]
    [Migration("20230408143109_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("ExchangeApp.DAL.Entities.CurrencyEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageCourseRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BuyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SellRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Code");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Code = "EUR",
                            AverageCourseRate = 1m,
                            PhotoUrl = "eur_flag.png",
                            Quantity = 0m,
                            Status = 1
                        },
                        new
                        {
                            Code = "CZK",
                            AverageCourseRate = 0m,
                            PhotoUrl = "czk_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "USD",
                            AverageCourseRate = 0m,
                            PhotoUrl = "usd_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "PLN",
                            AverageCourseRate = 0m,
                            PhotoUrl = "pln_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "JPY",
                            AverageCourseRate = 0m,
                            PhotoUrl = "jpn_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "GBP",
                            AverageCourseRate = 0m,
                            PhotoUrl = "gbp_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "CHF",
                            AverageCourseRate = 0m,
                            PhotoUrl = "chf_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "HUF",
                            AverageCourseRate = 0m,
                            PhotoUrl = "huf_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "CAD",
                            AverageCourseRate = 0m,
                            PhotoUrl = "cad_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "NOK",
                            AverageCourseRate = 0m,
                            PhotoUrl = "nok_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "BGN",
                            AverageCourseRate = 0m,
                            PhotoUrl = "bgn_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "RUB",
                            AverageCourseRate = 0m,
                            PhotoUrl = "rub_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "DKK",
                            AverageCourseRate = 0m,
                            PhotoUrl = "dkk_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "RON",
                            AverageCourseRate = 0m,
                            PhotoUrl = "ron_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "SEK",
                            AverageCourseRate = 0m,
                            PhotoUrl = "sek_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "TRY",
                            AverageCourseRate = 0m,
                            PhotoUrl = "try_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "AUD",
                            AverageCourseRate = 0m,
                            PhotoUrl = "aud_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "BRL",
                            AverageCourseRate = 0m,
                            PhotoUrl = "brl_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "CNY",
                            AverageCourseRate = 0m,
                            PhotoUrl = "cny_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "HKD",
                            AverageCourseRate = 0m,
                            PhotoUrl = "hkd_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "IDR",
                            AverageCourseRate = 0m,
                            PhotoUrl = "idr_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "ILS",
                            AverageCourseRate = 0m,
                            PhotoUrl = "ils_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "INR",
                            AverageCourseRate = 0m,
                            PhotoUrl = "inr_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "KRW",
                            AverageCourseRate = 0m,
                            PhotoUrl = "krw_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "MXN",
                            AverageCourseRate = 0m,
                            PhotoUrl = "mxn_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "MYR",
                            AverageCourseRate = 0m,
                            PhotoUrl = "myr_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "NZD",
                            AverageCourseRate = 0m,
                            PhotoUrl = "nzd_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "PHP",
                            AverageCourseRate = 0m,
                            PhotoUrl = "php_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "SGD",
                            AverageCourseRate = 0m,
                            PhotoUrl = "sgd_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "THB",
                            AverageCourseRate = 0m,
                            PhotoUrl = "thb_flag.png",
                            Quantity = 0m,
                            Status = 0
                        },
                        new
                        {
                            Code = "ZAR",
                            AverageCourseRate = 0m,
                            PhotoUrl = "zar_flag.png",
                            Quantity = 0m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.CurrencyHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AverageCourseRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyEntityCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyEntityCode");

                    b.ToTable("CurrenciesHistory");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Customers.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EvidenceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Operations.OperationEntityBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AverageCourseRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CourseRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrencyQuantityBefore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("Operations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("OperationEntityBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.TotalBalanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastTotalBalance")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Created")
                        .IsUnique();

                    b.ToTable("TotalBalances");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Customers.BusinessCustomerEntity", b =>
                {
                    b.HasBaseType("ExchangeApp.DAL.Entities.Customers.CustomerEntity");

                    b.Property<string>("ICO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeNameOfTheOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("BusinessCustomers");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Customers.IndividualCustomerEntity", b =>
                {
                    b.HasBaseType("ExchangeApp.DAL.Entities.Customers.CustomerEntity");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("IndividualCustomers");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Customers.MinorCustomerEntity", b =>
                {
                    b.HasBaseType("ExchangeApp.DAL.Entities.Customers.CustomerEntity");

                    b.ToTable("MinorCustomers");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Operations.DonationEntity", b =>
                {
                    b.HasBaseType("ExchangeApp.DAL.Entities.Operations.OperationEntityBase");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("DonationEntity");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Operations.TransactionEntity", b =>
                {
                    b.HasBaseType("ExchangeApp.DAL.Entities.Operations.OperationEntityBase");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("TransactionEntity");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.CurrencyHistoryEntity", b =>
                {
                    b.HasOne("ExchangeApp.DAL.Entities.CurrencyEntity", null)
                        .WithMany("History")
                        .HasForeignKey("CurrencyEntityCode");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Operations.OperationEntityBase", b =>
                {
                    b.HasOne("ExchangeApp.DAL.Entities.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Customers.BusinessCustomerEntity", b =>
                {
                    b.HasOne("ExchangeApp.DAL.Entities.Customers.CustomerEntity", null)
                        .WithOne()
                        .HasForeignKey("ExchangeApp.DAL.Entities.Customers.BusinessCustomerEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Customers.IndividualCustomerEntity", b =>
                {
                    b.HasOne("ExchangeApp.DAL.Entities.Customers.CustomerEntity", null)
                        .WithOne()
                        .HasForeignKey("ExchangeApp.DAL.Entities.Customers.IndividualCustomerEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Customers.MinorCustomerEntity", b =>
                {
                    b.HasOne("ExchangeApp.DAL.Entities.Customers.CustomerEntity", null)
                        .WithOne()
                        .HasForeignKey("ExchangeApp.DAL.Entities.Customers.MinorCustomerEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.Operations.TransactionEntity", b =>
                {
                    b.HasOne("ExchangeApp.DAL.Entities.Customers.CustomerEntity", "Customer")
                        .WithOne()
                        .HasForeignKey("ExchangeApp.DAL.Entities.Operations.TransactionEntity", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ExchangeApp.DAL.Entities.CurrencyEntity", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
