//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CurrencyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CurrencyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeApp.App.Resources.Texts.CurrencyResources", typeof(CurrencyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        public static string AUD {
            get {
                return ResourceManager.GetString("AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgaria.
        /// </summary>
        public static string BGN {
            get {
                return ResourceManager.GetString("BGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        public static string BRL {
            get {
                return ResourceManager.GetString("BRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string CAD {
            get {
                return ResourceManager.GetString("CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switzerland.
        /// </summary>
        public static string CHF {
            get {
                return ResourceManager.GetString("CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China.
        /// </summary>
        public static string CNY {
            get {
                return ResourceManager.GetString("CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string CZK {
            get {
                return ResourceManager.GetString("CZK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denmark.
        /// </summary>
        public static string DKK {
            get {
                return ResourceManager.GetString("DKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eurozone.
        /// </summary>
        public static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United kingdom.
        /// </summary>
        public static string GBP {
            get {
                return ResourceManager.GetString("GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honk Kong.
        /// </summary>
        public static string HKD {
            get {
                return ResourceManager.GetString("HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungary.
        /// </summary>
        public static string HUF {
            get {
                return ResourceManager.GetString("HUF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesia.
        /// </summary>
        public static string IDR {
            get {
                return ResourceManager.GetString("IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel.
        /// </summary>
        public static string ILS {
            get {
                return ResourceManager.GetString("ILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        public static string INR {
            get {
                return ResourceManager.GetString("INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iceland.
        /// </summary>
        public static string ISK {
            get {
                return ResourceManager.GetString("ISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        public static string JPY {
            get {
                return ResourceManager.GetString("JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Korea.
        /// </summary>
        public static string KRW {
            get {
                return ResourceManager.GetString("KRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        public static string MXN {
            get {
                return ResourceManager.GetString("MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysia.
        /// </summary>
        public static string MYR {
            get {
                return ResourceManager.GetString("MYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norway.
        /// </summary>
        public static string NOK {
            get {
                return ResourceManager.GetString("NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Zealand.
        /// </summary>
        public static string NZD {
            get {
                return ResourceManager.GetString("NZD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philippines.
        /// </summary>
        public static string PHP {
            get {
                return ResourceManager.GetString("PHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poland.
        /// </summary>
        public static string PLN {
            get {
                return ResourceManager.GetString("PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romania.
        /// </summary>
        public static string RON {
            get {
                return ResourceManager.GetString("RON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweden.
        /// </summary>
        public static string SEK {
            get {
                return ResourceManager.GetString("SEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singapore.
        /// </summary>
        public static string SGD {
            get {
                return ResourceManager.GetString("SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very long state name because sometimes we need to test label overflow. bla bla bla bla bla bla.
        /// </summary>
        public static string TEST {
            get {
                return ResourceManager.GetString("TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thailand.
        /// </summary>
        public static string THB {
            get {
                return ResourceManager.GetString("THB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string TRY {
            get {
                return ResourceManager.GetString("TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United states of America.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South Africa.
        /// </summary>
        public static string ZAR {
            get {
                return ResourceManager.GetString("ZAR", resourceCulture);
            }
        }
    }
}
