//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeApp.App.Resources.Texts.CustomerResources", typeof(CustomerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date:.
        /// </summary>
        public static string BirthDateLabel {
            get {
                return ResourceManager.GetString("BirthDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company address:.
        /// </summary>
        public static string BusinessAddressCompanyLabel {
            get {
                return ResourceManager.GetString("BusinessAddressCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name:.
        /// </summary>
        public static string BusinessCompanyNameLabel {
            get {
                return ResourceManager.GetString("BusinessCompanyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business person.
        /// </summary>
        public static string BusinessCustomer {
            get {
                return ResourceManager.GetString("BusinessCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification number of business person (if the number was assigned):.
        /// </summary>
        public static string BusinessIdentificationNumberLabel {
            get {
                return ResourceManager.GetString("BusinessIdentificationNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer detail.
        /// </summary>
        public static string CustomerDetailPageTitle {
            get {
                return ResourceManager.GetString("CustomerDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string DefaultNationalityPlaceholder {
            get {
                return ResourceManager.GetString("DefaultNationalityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not valid or missing..
        /// </summary>
        public static string ErrorMessage_AddressNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_AddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter at least one birth date or identification number..
        /// </summary>
        public static string ErrorMessage_BirthDateAndIdentificationNumberNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_BirthDateAndIdentificationNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company address not valid or missing..
        /// </summary>
        public static string ErrorMessage_BusinessAddressNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_BusinessAddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name not valid or missing..
        /// </summary>
        public static string ErrorMessage_BusinessCompanyNameNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_BusinessCompanyNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification number of business person not valid or missing..
        /// </summary>
        public static string ErrorMessage_BusinessIdentificationNumberNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_BusinessIdentificationNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence number not valid or missing..
        /// </summary>
        public static string ErrorMessage_EvidenceNumberNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_EvidenceNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name not valid or missing..
        /// </summary>
        public static string ErrorMessage_FirstNameNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_FirstNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification number has wrong format. (try for example 000101/9999, 000528/1). If customer is from country with another identification number format, fill only his birth date and the identification number entry set as empty..
        /// </summary>
        public static string ErrorMessage_IdentificationNumberNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_IdentificationNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name not valid or missing..
        /// </summary>
        public static string ErrorMessage_LastNameNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_LastNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence number:.
        /// </summary>
        public static string EvidenceNumberLabel {
            get {
                return ResourceManager.GetString("EvidenceNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal representative evidence number:.
        /// </summary>
        public static string EvidenceNumberLegalRepresentativeLabel {
            get {
                return ResourceManager.GetString("EvidenceNumberLegalRepresentativeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evidence type:.
        /// </summary>
        public static string EvidenceTypeLabel {
            get {
                return ResourceManager.GetString("EvidenceTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification number:.
        /// </summary>
        public static string IdentificationNumberLabel {
            get {
                return ResourceManager.GetString("IdentificationNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inidividual.
        /// </summary>
        public static string IndividualCustomer {
            get {
                return ResourceManager.GetString("IndividualCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor person.
        /// </summary>
        public static string MinorCustomer {
            get {
                return ResourceManager.GetString("MinorCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form is used for entering a minor who does not have an identity document.
        /// </summary>
        public static string MinorCustomerMainInfoLabel {
            get {
                return ResourceManager.GetString("MinorCustomerMainInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality:.
        /// </summary>
        public static string NationalityLabel {
            get {
                return ResourceManager.GetString("NationalityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer.
        /// </summary>
        public static string NewCustomerTitle {
            get {
                return ResourceManager.GetString("NewCustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string PersonTypeLabel {
            get {
                return ResourceManager.GetString("PersonTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For refugees, place of residence in a refugee camp.
        /// </summary>
        public static string RefugeesInfoLabel {
            get {
                return ResourceManager.GetString("RefugeesInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string WholeNameLabel {
            get {
                return ResourceManager.GetString("WholeNameLabel", resourceCulture);
            }
        }
    }
}
