//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DonationDetailPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DonationDetailPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeApp.App.Resources.Texts.DonationDetailPageResources", typeof(DonationDetailPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertCancelButton {
            get {
                return ResourceManager.GetString("AlertCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELED.
        /// </summary>
        public static string CanceledLabel {
            get {
                return ResourceManager.GetString("CanceledLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course rate:.
        /// </summary>
        public static string CourseRateLabel {
            get {
                return ResourceManager.GetString("CourseRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code:.
        /// </summary>
        public static string CurrencyCodeLabel {
            get {
                return ResourceManager.GetString("CurrencyCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time:.
        /// </summary>
        public static string DateAndTimeLabel {
            get {
                return ResourceManager.GetString("DateAndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation number:.
        /// </summary>
        public static string DonationNumberLabel {
            get {
                return ResourceManager.GetString("DonationNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation type:.
        /// </summary>
        public static string DonationTypeLabel {
            get {
                return ResourceManager.GetString("DonationTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee:.
        /// </summary>
        public static string EmployeeLabel {
            get {
                return ResourceManager.GetString("EmployeeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation detail.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder path for saving the files is missing. This folder can be set in the settings..
        /// </summary>
        public static string PdfDownloadAlertErrorMessage {
            get {
                return ResourceManager.GetString("PdfDownloadAlertErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been saved to your computer..
        /// </summary>
        public static string PdfDownloadAlertMessage {
            get {
                return ResourceManager.GetString("PdfDownloadAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF save.
        /// </summary>
        public static string PdfDownloadAlertTitle {
            get {
                return ResourceManager.GetString("PdfDownloadAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        public static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this donation? This event is irreversible..
        /// </summary>
        public static string StornoAlertConfirmationMessage {
            get {
                return ResourceManager.GetString("StornoAlertConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string StornoAlertConfirmationNo {
            get {
                return ResourceManager.GetString("StornoAlertConfirmationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation confirmation.
        /// </summary>
        public static string StornoAlertConfirmationTitle {
            get {
                return ResourceManager.GetString("StornoAlertConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string StornoAlertConfirmationYes {
            get {
                return ResourceManager.GetString("StornoAlertConfirmationYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is created total balance for this operation so you can&apos;t cancel it anymore..
        /// </summary>
        public static string StornoAlertErrorMessageClosedDonation {
            get {
                return ResourceManager.GetString("StornoAlertErrorMessageClosedDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in getting currencies..
        /// </summary>
        public static string StornoAlertErrorMessageCurrencyMissingException {
            get {
                return ResourceManager.GetString("StornoAlertErrorMessageCurrencyMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction cannot be canceled due to insufficient funds..
        /// </summary>
        public static string StornoAlertErrorMessageInsufficientMoney {
            get {
                return ResourceManager.GetString("StornoAlertErrorMessageInsufficientMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation failure.
        /// </summary>
        public static string StornoAlertErrorTitle {
            get {
                return ResourceManager.GetString("StornoAlertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction successfully canceled..
        /// </summary>
        public static string StornoAlertMessage {
            get {
                return ResourceManager.GetString("StornoAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation cancel.
        /// </summary>
        public static string StornoAlertTitle {
            get {
                return ResourceManager.GetString("StornoAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCELLED.
        /// </summary>
        public static string StornoLabel {
            get {
                return ResourceManager.GetString("StornoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download to chosen folder.
        /// </summary>
        public static string ToolTip_DownloadDonation {
            get {
                return ResourceManager.GetString("ToolTip_DownloadDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string ToolTip_PrintDonation {
            get {
                return ResourceManager.GetString("ToolTip_PrintDonation", resourceCulture);
            }
        }
    }
}
