//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeApp.App.Resources.Texts.MainPageResources", typeof(MainPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash register status.
        /// </summary>
        public static string CashRegisterStatusComboBoxItem {
            get {
                return ResourceManager.GetString("CashRegisterStatusComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course rates.
        /// </summary>
        public static string CourseRatesComboBoxItem {
            get {
                return ResourceManager.GetString("CourseRatesComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily total balance.
        /// </summary>
        public static string DailyTotalBalanceComboBoxItem {
            get {
                return ResourceManager.GetString("DailyTotalBalanceComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string DepositComboBoxItem {
            get {
                return ResourceManager.GetString("DepositComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        public static string DonationComboBoxTitle {
            get {
                return ResourceManager.GetString("DonationComboBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string EmployeePickerTitle {
            get {
                return ResourceManager.GetString("EmployeePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levy.
        /// </summary>
        public static string LevyComboBoxItem {
            get {
                return ResourceManager.GetString("LevyComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly total balance.
        /// </summary>
        public static string MonthlyTotalBalanceComboBoxItem {
            get {
                return ResourceManager.GetString("MonthlyTotalBalanceComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of todays operations:.
        /// </summary>
        public static string OperationsInDayLabel {
            get {
                return ResourceManager.GetString("OperationsInDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations list.
        /// </summary>
        public static string OperationsListComboBoxItem {
            get {
                return ResourceManager.GetString("OperationsListComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string OthersComboBoxTitle {
            get {
                return ResourceManager.GetString("OthersComboBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit calculation.
        /// </summary>
        public static string ProfitCalculationComboBoxItem {
            get {
                return ResourceManager.GetString("ProfitCalculationComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storno.
        /// </summary>
        public static string StornoComboBoxItem {
            get {
                return ResourceManager.GetString("StornoComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balance.
        /// </summary>
        public static string TotalBalanceComboBoxTitle {
            get {
                return ResourceManager.GetString("TotalBalanceComboBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        public static string TradeComboBoxTitle {
            get {
                return ResourceManager.GetString("TradeComboBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string TransactionComboBoxItem {
            get {
                return ResourceManager.GetString("TransactionComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string WithdrawComboBoxItem {
            get {
                return ResourceManager.GetString("WithdrawComboBoxItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly total balance.
        /// </summary>
        public static string YearlyTotalBalanceComboBoxItem {
            get {
                return ResourceManager.GetString("YearlyTotalBalanceComboBoxItem", resourceCulture);
            }
        }
    }
}
