//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrinterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrinterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeApp.App.Resources.Texts.PrinterResources", typeof(PrinterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in {0}.
        /// </summary>
        public static string AmountTableHeader {
            get {
                return ResourceManager.GetString("AmountTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average course rate.
        /// </summary>
        public static string AverageCourseRateTableHeader {
            get {
                return ResourceManager.GetString("AverageCourseRateTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string BuyTransactionHeader {
            get {
                return ResourceManager.GetString("BuyTransactionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string CanceledHeaderTitle {
            get {
                return ResourceManager.GetString("CanceledHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course rate.
        /// </summary>
        public static string CourseRateTableHeader {
            get {
                return ResourceManager.GetString("CourseRateTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code.
        /// </summary>
        public static string CurrencyCodeTableHeader {
            get {
                return ResourceManager.GetString("CurrencyCodeTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        public static string FolderNameBuy {
            get {
                return ResourceManager.GetString("FolderNameBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deposit.
        /// </summary>
        public static string FolderNameDeposit {
            get {
                return ResourceManager.GetString("FolderNameDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to levy.
        /// </summary>
        public static string FolderNameLevy {
            get {
                return ResourceManager.GetString("FolderNameLevy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sell.
        /// </summary>
        public static string FolderNameSell {
            get {
                return ResourceManager.GetString("FolderNameSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to withdraw.
        /// </summary>
        public static string FolderNameWithdraw {
            get {
                return ResourceManager.GetString("FolderNameWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for visiting!.
        /// </summary>
        public static string FooterNiceSentence {
            get {
                return ResourceManager.GetString("FooterNiceSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string IdentificationNumberCompanyLabel {
            get {
                return ResourceManager.GetString("IdentificationNumberCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction number:.
        /// </summary>
        public static string IdentificationNumberLabelBeforeIdNumber {
            get {
                return ResourceManager.GetString("IdentificationNumberLabelBeforeIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string NoteLabel {
            get {
                return ResourceManager.GetString("NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount paid:.
        /// </summary>
        public static string PaidAmountLabel {
            get {
                return ResourceManager.GetString("PaidAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string PhoneAbbreviationLabel {
            get {
                return ResourceManager.GetString("PhoneAbbreviationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QuantityTableHeader {
            get {
                return ResourceManager.GetString("QuantityTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount received:.
        /// </summary>
        public static string ReceivedAmountLabel {
            get {
                return ResourceManager.GetString("ReceivedAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding:.
        /// </summary>
        public static string RoundingLabel {
            get {
                return ResourceManager.GetString("RoundingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string SellTransactionHeader {
            get {
                return ResourceManager.GetString("SellTransactionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string SignatureLabel {
            get {
                return ResourceManager.GetString("SignatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin:.
        /// </summary>
        public static string TinNumberCompanyLabel {
            get {
                return ResourceManager.GetString("TinNumberCompanyLabel", resourceCulture);
            }
        }
    }
}
