//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrinterTotalBalanceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrinterTotalBalanceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeApp.App.Resources.Texts.PrinterTotalBalanceResources", typeof(PrinterTotalBalanceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount total:.
        /// </summary>
        public static string AmountTotalSummary {
            get {
                return ResourceManager.GetString("AmountTotalSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual total balance.
        /// </summary>
        public static string AnnualTotalBalance {
            get {
                return ResourceManager.GetString("AnnualTotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily total balance.
        /// </summary>
        public static string DailyTotalBalance {
            get {
                return ResourceManager.GetString("DailyTotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference:.
        /// </summary>
        public static string DifferenceLabel {
            get {
                return ResourceManager.GetString("DifferenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daily.
        /// </summary>
        public static string FolderNameDaily {
            get {
                return ResourceManager.GetString("FolderNameDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monthly.
        /// </summary>
        public static string FolderNameMonthly {
            get {
                return ResourceManager.GetString("FolderNameMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string ICO_headerText {
            get {
                return ResourceManager.GetString("ICO_headerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ListHeaderItemAmount {
            get {
                return ResourceManager.GetString("ListHeaderItemAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount foreign currency.
        /// </summary>
        public static string ListHeaderItemAmountForeignCurrency {
            get {
                return ResourceManager.GetString("ListHeaderItemAmountForeignCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount in dom. currency.
        /// </summary>
        public static string ListHeaderItemAmountInDomesticCurrency {
            get {
                return ResourceManager.GetString("ListHeaderItemAmountInDomesticCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string ListHeaderItemBalance {
            get {
                return ResourceManager.GetString("ListHeaderItemBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string ListHeaderItemBuy {
            get {
                return ResourceManager.GetString("ListHeaderItemBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course rate.
        /// </summary>
        public static string ListHeaderItemCourseRate {
            get {
                return ResourceManager.GetString("ListHeaderItemCourseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code.
        /// </summary>
        public static string ListHeaderItemCurrencyCode {
            get {
                return ResourceManager.GetString("ListHeaderItemCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        public static string ListHeaderItemCustomerName {
            get {
                return ResourceManager.GetString("ListHeaderItemCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ListHeaderItemDate {
            get {
                return ResourceManager.GetString("ListHeaderItemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string ListHeaderItemDateTime {
            get {
                return ResourceManager.GetString("ListHeaderItemDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string ListHeaderItemDeposit {
            get {
                return ResourceManager.GetString("ListHeaderItemDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate value.
        /// </summary>
        public static string ListHeaderItemExchangeRateValue {
            get {
                return ResourceManager.GetString("ListHeaderItemExchangeRateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final state.
        /// </summary>
        public static string ListHeaderItemFinalState {
            get {
                return ResourceManager.GetString("ListHeaderItemFinalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification card number.
        /// </summary>
        public static string ListHeaderItemIdentificationCardNumber {
            get {
                return ResourceManager.GetString("ListHeaderItemIdentificationCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial state.
        /// </summary>
        public static string ListHeaderItemInitialState {
            get {
                return ResourceManager.GetString("ListHeaderItemInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levy.
        /// </summary>
        public static string ListHeaderItemLevy {
            get {
                return ResourceManager.GetString("ListHeaderItemLevy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string ListHeaderItemNote {
            get {
                return ResourceManager.GetString("ListHeaderItemNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ListHeaderItemOperationId {
            get {
                return ResourceManager.GetString("ListHeaderItemOperationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation type.
        /// </summary>
        public static string ListHeaderItemOperationType {
            get {
                return ResourceManager.GetString("ListHeaderItemOperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string ListHeaderItemProfit {
            get {
                return ResourceManager.GetString("ListHeaderItemProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string ListHeaderItemQuantity {
            get {
                return ResourceManager.GetString("ListHeaderItemQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding.
        /// </summary>
        public static string ListHeaderItemRounding {
            get {
                return ResourceManager.GetString("ListHeaderItemRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string ListHeaderItemSell {
            get {
                return ResourceManager.GetString("ListHeaderItemSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ListHeaderItemState {
            get {
                return ResourceManager.GetString("ListHeaderItemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string ListHeaderItemTotal {
            get {
                return ResourceManager.GetString("ListHeaderItemTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ListHeaderItemType {
            get {
                return ResourceManager.GetString("ListHeaderItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string ListHeaderItemWithdraw {
            get {
                return ResourceManager.GetString("ListHeaderItemWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly total balance.
        /// </summary>
        public static string MonthlyTotalBalance {
            get {
                return ResourceManager.GetString("MonthlyTotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit total:.
        /// </summary>
        public static string ProfitTotalLabel {
            get {
                return ResourceManager.GetString("ProfitTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy list - abbreviated.
        /// </summary>
        public static string SectionHeaderBuyTransactionsAbbreviated {
            get {
                return ResourceManager.GetString("SectionHeaderBuyTransactionsAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash register status while creating total balance.
        /// </summary>
        public static string SectionHeaderCashRegisterStatusInTotalBalanceTime {
            get {
                return ResourceManager.GetString("SectionHeaderCashRegisterStatusInTotalBalanceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies movement.
        /// </summary>
        public static string SectionHeaderCurrenciesMovement {
            get {
                return ResourceManager.GetString("SectionHeaderCurrenciesMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency amounts in domestic currency.
        /// </summary>
        public static string SectionHeaderCurrencyAmountsInDomesticCurrency {
            get {
                return ResourceManager.GetString("SectionHeaderCurrencyAmountsInDomesticCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donations.
        /// </summary>
        public static string SectionHeaderDonationOperations {
            get {
                return ResourceManager.GetString("SectionHeaderDonationOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly report - overview.
        /// </summary>
        public static string SectionHeaderMonthlyTotalOperationsNumber {
            get {
                return ResourceManager.GetString("SectionHeaderMonthlyTotalOperationsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other operations.
        /// </summary>
        public static string SectionHeaderOtherOperations {
            get {
                return ResourceManager.GetString("SectionHeaderOtherOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit - abbreviated.
        /// </summary>
        public static string SectionHeaderProfitAbbreviated {
            get {
                return ResourceManager.GetString("SectionHeaderProfitAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit - complete.
        /// </summary>
        public static string SectionHeaderProfitComplete {
            get {
                return ResourceManager.GetString("SectionHeaderProfitComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase receipt - complete.
        /// </summary>
        public static string SectionHeaderPurchaseReceiptComplete {
            get {
                return ResourceManager.GetString("SectionHeaderPurchaseReceiptComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales receipt - complete.
        /// </summary>
        public static string SectionHeaderSalesReceiptComplete {
            get {
                return ResourceManager.GetString("SectionHeaderSalesReceiptComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell list - abbreviated.
        /// </summary>
        public static string SectionHeaderSellTransactionsAbbreviated {
            get {
                return ResourceManager.GetString("SectionHeaderSellTransactionsAbbreviated", resourceCulture);
            }
        }
    }
}
