//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeApp.App.Resources.Texts.SettingsPageResources", typeof(SettingsPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting branch info.
        /// </summary>
        public static string BranchInfoListItem {
            get {
                return ResourceManager.GetString("BranchInfoListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting company info.
        /// </summary>
        public static string CompanyInfoListItem {
            get {
                return ResourceManager.GetString("CompanyInfoListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course rates.
        /// </summary>
        public static string CourseRatesListItem {
            get {
                return ResourceManager.GetString("CourseRatesListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course rates sales.
        /// </summary>
        public static string CourseRatesSalesListItem {
            get {
                return ResourceManager.GetString("CourseRatesSalesListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee settings.
        /// </summary>
        public static string EmployeeListItem {
            get {
                return ResourceManager.GetString("EmployeeListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseInfoListItem {
            get {
                return ResourceManager.GetString("LicenseInfoListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic operations saving.
        /// </summary>
        public static string OperationsAutomaticSaveListItem {
            get {
                return ResourceManager.GetString("OperationsAutomaticSaveListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balances settings.
        /// </summary>
        public static string TotalBalanceListItem {
            get {
                return ResourceManager.GetString("TotalBalanceListItem", resourceCulture);
            }
        }
    }
}
