//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TotalBalancePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TotalBalancePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeApp.App.Resources.Texts.TotalBalancePageResources", typeof(TotalBalancePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AlertButtonNo {
            get {
                return ResourceManager.GetString("AlertButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertButtonOk {
            get {
                return ResourceManager.GetString("AlertButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AlertButtonYes {
            get {
                return ResourceManager.GetString("AlertButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to create annual total balance for year: {0}?.
        /// </summary>
        public static string AlertConfirmationAnnualMessage {
            get {
                return ResourceManager.GetString("AlertConfirmationAnnualMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to create daily total balance for day: {0}?.
        /// </summary>
        public static string AlertConfirmationDailyMessage {
            get {
                return ResourceManager.GetString("AlertConfirmationDailyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to create monthly total balance for month: {0}?.
        /// </summary>
        public static string AlertConfirmationMonthlyMessage {
            get {
                return ResourceManager.GetString("AlertConfirmationMonthlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balance create confirmation.
        /// </summary>
        public static string AlertConfirmationTitle {
            get {
                return ResourceManager.GetString("AlertConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balance created..
        /// </summary>
        public static string AlertMessageCreationDone {
            get {
                return ResourceManager.GetString("AlertMessageCreationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balance PDF downloaded to your computer..
        /// </summary>
        public static string AlertMessageDownloaded {
            get {
                return ResourceManager.GetString("AlertMessageDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same total balance already exists..
        /// </summary>
        public static string AlertMessageErrorAlreadyExists {
            get {
                return ResourceManager.GetString("AlertMessageErrorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create a monthly total balance, it is necessary to have closed all operations using daily closings..
        /// </summary>
        public static string AlertMessageErrorCanNotCreateMonthlyBalance {
            get {
                return ResourceManager.GetString("AlertMessageErrorCanNotCreateMonthlyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balance was successfully created..
        /// </summary>
        public static string AlertTitleCreationDone {
            get {
                return ResourceManager.GetString("AlertTitleCreationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balance download.
        /// </summary>
        public static string AlertTitleDownloaded {
            get {
                return ResourceManager.GetString("AlertTitleDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balance creation failure.
        /// </summary>
        public static string AlertTitleErrorCreation {
            get {
                return ResourceManager.GetString("AlertTitleErrorCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create annual total balance.
        /// </summary>
        public static string CreateTotalBalanceAnnual {
            get {
                return ResourceManager.GetString("CreateTotalBalanceAnnual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create daily total balance.
        /// </summary>
        public static string CreateTotalBalanceDaily {
            get {
                return ResourceManager.GetString("CreateTotalBalanceDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create monthly total balance.
        /// </summary>
        public static string CreateTotalBalanceMonthly {
            get {
                return ResourceManager.GetString("CreateTotalBalanceMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the background of the date picker is red, its value is not taken into account during filtering..
        /// </summary>
        public static string DatePickerHint {
            get {
                return ResourceManager.GetString("DatePickerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterButtonText {
            get {
                return ResourceManager.GetString("FilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string FilterDateFromLabel {
            get {
                return ResourceManager.GetString("FilterDateFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until:.
        /// </summary>
        public static string FilterDateUntilLabel {
            get {
                return ResourceManager.GetString("FilterDateUntilLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balance type:.
        /// </summary>
        public static string FilterPickerTitle {
            get {
                return ResourceManager.GetString("FilterPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ListHeaderItemDate {
            get {
                return ResourceManager.GetString("ListHeaderItemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string ListHeaderItemId {
            get {
                return ResourceManager.GetString("ListHeaderItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ListHeaderItemType {
            get {
                return ResourceManager.GetString("ListHeaderItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total balance.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string ToolTip_ClearFilter {
            get {
                return ResourceManager.GetString("ToolTip_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download to chosen folder.
        /// </summary>
        public static string ToolTip_DownloadTotalBalance {
            get {
                return ResourceManager.GetString("ToolTip_DownloadTotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string ToolTip_PrintTotalBalance {
            get {
                return ResourceManager.GetString("ToolTip_PrintTotalBalance", resourceCulture);
            }
        }
    }
}
