//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeApp.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransactionPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeApp.App.Resources.Texts.TransactionPageResources", typeof(TransactionPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity from:.
        /// </summary>
        public static string AmountFromLabel {
            get {
                return ResourceManager.GetString("AmountFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string AmountLabel {
            get {
                return ResourceManager.GetString("AmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to:.
        /// </summary>
        public static string AmountToLabel {
            get {
                return ResourceManager.GetString("AmountToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course rate:.
        /// </summary>
        public static string CourseRateLabel {
            get {
                return ResourceManager.GetString("CourseRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency from:.
        /// </summary>
        public static string CurrencyFromLabel {
            get {
                return ResourceManager.GetString("CurrencyFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in cash register:.
        /// </summary>
        public static string CurrencyInCashRegisterAmountLabel {
            get {
                return ResourceManager.GetString("CurrencyInCashRegisterAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency to:.
        /// </summary>
        public static string CurrencyToLabel {
            get {
                return ResourceManager.GetString("CurrencyToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The course rate can not exceed the opposite course rate..
        /// </summary>
        public static string ErrorMessage_CourseRateExceededOtherOne {
            get {
                return ResourceManager.GetString("ErrorMessage_CourseRateExceededOtherOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course rate can not be empty, 0 or less than zero..
        /// </summary>
        public static string ErrorMessage_CourseRateNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_CourseRateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One selected currency must be domestic and the other one must be different..
        /// </summary>
        public static string ErrorMessage_CurrencySelection {
            get {
                return ResourceManager.GetString("ErrorMessage_CurrencySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money in cash register..
        /// </summary>
        public static string ErrorMessage_InsufficientMoneyInCashRegister {
            get {
                return ResourceManager.GetString("ErrorMessage_InsufficientMoneyInCashRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity from can not be empty, 0 or less than zero..
        /// </summary>
        public static string ErrorMessage_QuantityFromNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_QuantityFromNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to can not be empty, 0 or less than zero..
        /// </summary>
        public static string ErrorMessage_QuantityToNotValid {
            get {
                return ResourceManager.GetString("ErrorMessage_QuantityToNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For payment:.
        /// </summary>
        public static string ForPaymentLabel {
            get {
                return ResourceManager.GetString("ForPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original course rate: {0}.
        /// </summary>
        public static string OriginalCourseRateLabel {
            get {
                return ResourceManager.GetString("OriginalCourseRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment:.
        /// </summary>
        public static string PaymentLabel {
            get {
                return ResourceManager.GetString("PaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding:.
        /// </summary>
        public static string RoundingLabel {
            get {
                return ResourceManager.GetString("RoundingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip:.
        /// </summary>
        public static string TipLabel {
            get {
                return ResourceManager.GetString("TipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pay:.
        /// </summary>
        public static string ToPayLabel {
            get {
                return ResourceManager.GetString("ToPayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string TransactionTitle {
            get {
                return ResourceManager.GetString("TransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction type:.
        /// </summary>
        public static string TransactionTypeLabel {
            get {
                return ResourceManager.GetString("TransactionTypeLabel", resourceCulture);
            }
        }
    }
}
